sonar.projectKey=matthisphan_ValorisationDonneeMeteo
sonar.organization=matthisphan
sonar.host.url=https://sonarcloud.io

sonar.sources=backend,frontend
sonar.exclusions=**/node_modules/**,**/tests/**

sonar.python.version=3.11
